### ISSUE TITLE
请问是多数据源的吗，可以自定义生成各种数据库格式的增删改查代码吗

### ISSUE THREAD

**Issue by wangzhibinhttp** [christioner/RuoYi-master-sqlserver#1]
请问是多数据源的吗，可以自定义生成各种数据库格式的增删改查代码吗，如mysql,oracle ,sqlserver

**Comment by wangzhibinhttp** [comment]
还要没comment 表注释功能，无法为SQL server表取名，就无法识别然后自动生成代码了是如何解决的谢谢

**Comment by wangzhibinhttp** [comment]
SUBSTRING_INDEX' 不是可以识别的 内置函数名称。
改这个SELECT SUBSTRING(#{columnComment}, 1, CHARINDEX(' ', #{columnComment}) - 1)也无法生效

**Comment by christioner** [comment]
> 请问是多数据源的吗，可以自定义生成各种数据库格式的增删改查代码吗，如mysql,oracle ,sqlserver

ruoyi本身就是支持多数据源的，只是各个数据源所用到的sql代码有所差异，这部分是需要自行修改的

**Comment by christioner** [comment]
> 还要没comment 表注释功能，无法为SQL server表取名，就无法识别然后自动生成代码了是如何解决的谢谢

comment不是必须的吧，代码生成器这块我还没修改完，表结构变更和修改，在我自己使用过程中是用原生的生成器，出来之后修改一下就好了

**Comment by christioner** [comment]
> SUBSTRING_INDEX' 不是可以识别的 内置函数名称。 改这个SELECT SUBSTRING(#{columnComment}, 1, CHARINDEX(' ', #{columnComment}) - 1)也无法生效

我看你应该是想要研究这个框架，你参考一下官网上面提供的各种版本，我记得也有修改为sqlserver的，看看有没有你需要的解决方案

http://doc.ruoyi.vip/ruoyi/document/xmkz.html#%E5%90%8E%E5%8F%B0%E6%89%A9%E5%B1%95
